server:
  port: 8123
  servlet:
    context-path: /api
    session:
      timeout: 2592000
spring:
  application:
    name: picture
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/picture
    username: root
    password: 123456
  servlet:
    multipart:
          max-file-size: 10MB
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout: 5000
  session:
    redis:
      flush-mode: on_save
      namespace: spring:session






mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # ????????????
      logic-delete-value: 1 # ?????????? 1?
      logic-not-delete-value: 0 # ?????????? 0?

# springdoc-openapi????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yin.picture
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn

# ????????????????
cos:
  client:
    host:
    secretId:
    secretKey:
    region:
    bucket:
